#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 -v DATABASE_USER="$DATABASE_USER" -v DATABASE_NAME="$DATABASE_NAME" -v POSTGRES_PASSWORD="'$POSTGRES_PASSWORD'" --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER :DATABASE_USER WITH ENCRYPTED PASSWORD :POSTGRES_PASSWORD;
    CREATE DATABASE :DATABASE_NAME;
    GRANT ALL PRIVILEGES ON DATABASE :DATABASE_NAME TO :DATABASE_NAME;
EOSQL
